import 'package:flutter/material.dart';

/// Hand-built schemes. Neutrals carry a slight teal bias — not pure grey.
///
/// Reviewed against WCAG AA for `onSurface` on `surface` in both modes.
/// Primary is a deep teal so filled buttons stay readable; "ok" states in
/// [statusColors] reuse this family instead of green, so overdue (orange)
/// stays distinct for red–green colour blindness.
abstract final class AppColors {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF0F6E6A),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD5EFEB),
    onPrimaryContainer: Color(0xFF0A3D3A),
    secondary: Color(0xFF4A5C62),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFD5DEE2),
    onSecondaryContainer: Color(0xFF1C2A2E),
    tertiary: Color(0xFFB45309),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFE8D0),
    onTertiaryContainer: Color(0xFF5C2C05),
    error: Color(0xFFB42318),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFEE4E2),
    onErrorContainer: Color(0xFF7A271A),
    surface: Color(0xFFF4F6F6),
    onSurface: Color(0xFF1A2324),
    onSurfaceVariant: Color(0xFF3F4C4E),
    outline: Color(0xFF6F7C7E),
    outlineVariant: Color(0xFFBEC8C9),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF2F3738),
    onInverseSurface: Color(0xFFEFF1F1),
    inversePrimary: Color(0xFF7ED4CE),
    surfaceTint: Color(0xFF0F6E6A),
    surfaceDim: Color(0xFFD5D9D9),
    surfaceBright: Color(0xFFF8FAFA),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFEEF1F1),
    surfaceContainer: Color(0xFFE8ECEC),
    surfaceContainerHigh: Color(0xFFE2E7E7),
    surfaceContainerHighest: Color(0xFFDCE2E2),
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF7ED4CE),
    onPrimary: Color(0xFF003734),
    primaryContainer: Color(0xFF0A4A47),
    onPrimaryContainer: Color(0xFFC5F3EF),
    secondary: Color(0xFFB5C4C8),
    onSecondary: Color(0xFF1F2C30),
    secondaryContainer: Color(0xFF354348),
    onSecondaryContainer: Color(0xFFD5DEE2),
    tertiary: Color(0xFFF0B27A),
    onTertiary: Color(0xFF4A2800),
    tertiaryContainer: Color(0xFF6B3A08),
    onTertiaryContainer: Color(0xFFFFDDB8),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF121717),
    onSurface: Color(0xFFE2E8E8),
    onSurfaceVariant: Color(0xFFBEC8C9),
    outline: Color(0xFF889294),
    outlineVariant: Color(0xFF3F4C4E),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFFE2E8E8),
    onInverseSurface: Color(0xFF2F3738),
    inversePrimary: Color(0xFF0F6E6A),
    surfaceTint: Color(0xFF7ED4CE),
    surfaceDim: Color(0xFF121717),
    surfaceBright: Color(0xFF383E3E),
    surfaceContainerLowest: Color(0xFF0D1111),
    surfaceContainerLow: Color(0xFF1A2020),
    surfaceContainer: Color(0xFF1E2424),
    surfaceContainerHigh: Color(0xFF282E2E),
    surfaceContainerHighest: Color(0xFF333939),
  );
}
